import { Equality } from '@/types/enums';
import { RuleCategory } from '../rule';
import {
  FORGE_1_12_MISSING_DEPENDENCIES,
  FORGE_1_16_MISSING_DEPENDENCIES,
  FORGE_1_7_10_MISSING_DEPENDENCIES,
  FORGE_DIFFERENT_MODLOADER_MOD,
  FORGE_DUPLICATE_MODS,
  FORGE_MODERN_MISSING_DEPENDENCIES,
  FORGE_MODLOADING_ERROR,
  FORGE_OPTIFINE,
  FORGE_UNSUPPORTED_OPTIONAL_DEPENDENCIES,
  FORGE_WRONG_JAVA_8,
} from './rules';

export const FORGE_RULES: RuleCategory = {
  versionChecks: [
    {
      attribute: 'forgeVersion',
      equality: Equality.GTE,
      version: '0.0.1',
    },
  ],
  rules: [
    FORGE_OPTIFINE,
    FORGE_1_7_10_MISSING_DEPENDENCIES,
    FORGE_1_12_MISSING_DEPENDENCIES,
    FORGE_1_16_MISSING_DEPENDENCIES,
    FORGE_MODERN_MISSING_DEPENDENCIES,
    FORGE_UNSUPPORTED_OPTIONAL_DEPENDENCIES,
    FORGE_WRONG_JAVA_8,
    FORGE_DIFFERENT_MODLOADER_MOD,
    FORGE_DUPLICATE_MODS,
    FORGE_MODLOADING_ERROR,
  ],
};

export default FORGE_RULES;
